[build]
target = "x86_64-unknown-none"
rustflags = [
    "-Cforce-frame-pointers=yes",
    "-Csymbol-mangling-version=v0",
    "-Cforce-unwind-tables"
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]